// Generated by auto imports
export {}
declare global {
  const useRuntimeConfig: (event?: import('h3').H3Event) => import('nuxt/schema').RuntimeConfig
  const useAppConfig: () => import('nuxt/schema').AppConfig
  const defineAppConfig: <C extends import('nuxt/schema').AppConfigInput>(config: C) => C
  const createError: typeof import('h3')['createError']
  const setResponseStatus: typeof import('h3')['setResponseStatus']
  const $date: typeof import('../../core/utils/$date').$date
  const generateUUID: typeof import('../../core/utils/generate-uuid').generateUUID
  const get: typeof import('lodash-es').get
  const isDev: typeof import('../../core/utils/is-dev').isDev
  const isEmpty: typeof import('lodash-es').isEmpty
  const isEqual: typeof import('lodash-es').isEqual
  const isNil: typeof import('lodash-es').isNil
  const omit: typeof import('lodash-es').omit
  const parseValue: typeof import('../../core/utils/parse-value').parseValue
  const pick: typeof import('lodash-es').pick
  const set: typeof import('lodash-es').set
  const tMarker: typeof import('../../core/utils/t-marker').tMarker
  const z: typeof import('zod').z
}