const _comparator0 = {
  EQUAL: 'eq',
  NOT_EQUAL: 'not.eq',
  IN: 'in',
  NOT_IN: 'not.in',
  LIKE: 'like',
  CONTAINS: 'cs',
  STARTS_WITH: 'stw',
  ENDS_WITH: 'enw',
  NOT_LIKE: 'not.like',
  NOT_CONTAINS: 'not.cs',
  NOT_STARTS_WITH: 'not.stw',
  NOT_ENDS_WITH: 'not.enw',
  GREATER_THAN: 'gt',
  LESS_THAN: 'lt',
  GREATER_THAN_OR_EQUAL: 'gte',
  LESS_THAN_OR_EQUAL: 'lte',
  IS: 'is',
  NOT_IS: 'is.not',
  IN_EVERY: 'in.every',
  IN_NONE: 'in.none',
  IS_EMPTY: 'is.$empty',
  NOT_IS_EMPTY: 'is.not.$empty',
}
export const ComparatorEnum = { ..._comparator0 } as const
export type ComparatorEnum = (typeof ComparatorEnum)[keyof typeof ComparatorEnum]
